# Auto-generated by calibrate_via_fk.py
# Paste these into sensor_fusion.py, replacing
# CALIBRATION_PHYSICAL_PTS / CALIBRATION_PIXEL_PTS:
#
#   CALIBRATION_PHYSICAL_PTS = [(5.0, 0.0), (8.0, 6.0), (11.0, -6.0), (11.0, 0.0), (11.0, 3.0), (11.0, 6.0), (14.0, -6.0), (14.0, -3.0), (14.0, 0.0), (14.0, 3.0), (14.0, 6.0), (17.0, -6.0), (17.0, -3.0), (17.0, 0.0), (17.0, 3.0)]
#   CALIBRATION_PIXEL_PTS    = [(435.0, 477.0), (545.0, 401.0), (506.0, 528.0), (532.5, 446.0), (574.0, 439.5), (564.0, 400.0), (561.0, 493.0), (571.0, 476.0), (599.0, 455.0), (611.0, 436.0), (590.0, 378.0), (606.0, 409.0), (618.0, 411.0), (632.0, 415.0), (633.0, 390.0)]
#   mapper = LocalAffineMapper(CALIBRATION_PHYSICAL_PTS, CALIBRATION_PIXEL_PTS)
